PHSS/Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PHSS.Controllers
{
    [Authorize(Roles ="Admin")]
    public class DataController : Controller
    {
        // GET: Data
        public ActionResult Index(string School = "", string Under = "", string Team = "", string Result = "", string Division = "", string Fixture = "", string Log = "", string Season = "", string Location = "")
        {
            if (School != "")
            {
                return RedirectToAction("Index", "SchoolModels");
            }

            if (Under != "")
            {
                return RedirectToAction("Index", "AgeGroupModels");
            }

            if (Team != "")
            {
                return RedirectToAction("Index", "TeamModels");
            }

            if (Result != "")
            {
                return RedirectToAction("Index", "ResultModels");
            }

            if (Division != "")
            {
                return RedirectToAction("Index", "DivisionModels");
            }

            if (Fixture != "")
            {
                return RedirectToAction("Index", "FixtureModels");
            }

            if (Log != "")
            {
                return RedirectToAction("Index", "LogModels");
            }

            if (Season != "")
            {
                return RedirectToAction("Index", "SeasonModels");
            }

            if (Location != "")
            {
                return RedirectToAction("Index", "LocationModels");
            }

            return View();
        }
    }
}

PHSS/Controllers/WebsiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PHSS.Models;
using PHSS.ViewModels;
using Newtonsoft.Json;

namespace PHSS.Controllers
{
    [AllowAnonymous]
    public class WebsiteController : Controller
    {
        private static ApplicationDbContext db = new ApplicationDbContext();

        private static int MainDivisionId; //Stores division change
        private static int MainAgeGroupId; // Stores age group change

        // GET: Website
        public ActionResult Index()
        {
            //Required list of objects for the index page, these are to be added to the
            //index view model
            

            int DivisionId = db.Divisions.FirstOrDefault().DivisionId;
            int AgeGroupId = db.AgeGroup.FirstOrDefault().AgeGroupID;

            List<FixtureModel> Fixtures = db.Fixtures.Where(f => f.Team1.DivisionId == DivisionId && f.Team1.AgeGroupId == AgeGroupId && f.Executed == false || f.Matchdate < DateTime.Now).ToList();
            List<ResultModel> Results = db.Results.Where(r => r.Fixtures.Team1.DivisionId == DivisionId && r.Fixtures.Team1.AgeGroupId == AgeGroupId && r.Fixtures.Executed == false || r.Fixtures.Matchdate > DateTime.Now).ToList();
            List<LogModel> Logs = db.Logs.Where(l => l.Team.DivisionId == DivisionId && l.Team.AgeGroupId == AgeGroupId).ToList();

            //Sorting the logs according to league standards
            SortLogs(Logs);

            ViewBag.DivisionId = new SelectList(db.Divisions, "DivisionId", "DivisionName");
            ViewBag.AgeGroupId = new SelectList(db.AgeGroup, "AgeGroupId", "AgeGroupName");

            WebsiteIndexViewModel IndexPage = new WebsiteIndexViewModel(Fixtures, Results, Logs);

            return View(IndexPage);
        }

        public ActionResult Logs()
        {

            ViewBag.DivisionId = new SelectList(db.Divisions, "DivisionId", "DivisionName");
            ViewBag.AgeGroupId = new SelectList(db.AgeGroup, "AgeGroupId", "AgeGroupName");

            int AgeGroupId, DivisionId;

            //If a division has not been selected when the view all logs link has been clicked on, then use the first division in the table
            if (MainDivisionId == 0)
            {
                DivisionId = db.Divisions.FirstOrDefault().DivisionId;
            }
            else
            {
                DivisionId = MainDivisionId;
            }

            //If a division has not been selected when the view all logs link has been clicked on, then use the first division in the table
            if (MainAgeGroupId == 0)
            {
                AgeGroupId = db.AgeGroup.FirstOrDefault().AgeGroupID;
            }
            else
            {
                AgeGroupId = MainAgeGroupId;
            }

            List<LogModel> Logs = db.Logs.Where(l => l.Team.DivisionId == DivisionId && l.Team.AgeGroupId == AgeGroupId).ToList();

            return View(Logs);
        }

        [HttpGet]
        public ActionResult Fixtures()
        {
            ViewBag.DivisionId = new SelectList(db.Divisions, "DivisionId", "DivisionName");
            ViewBag.AgeGroupId = new SelectList(db.AgeGroup, "AgeGroupId", "AgeGroupName");

            int AgeGroupId, DivisionId;

            //If a division has not been selected when the view all logs link has been clicked on, then use the first division in the table
            if (MainDivisionId == 0)
            {
                DivisionId = db.Divisions.FirstOrDefault().DivisionId;
            }
            else
            {
                DivisionId = MainDivisionId;
            }

            //If a division has not been selected when the view all logs link has been clicked on, then use the first division in the table
            if (MainAgeGroupId == 0)
            {
                AgeGroupId = db.AgeGroup.FirstOrDefault().AgeGroupID;
            }
            else
            {
                AgeGroupId = MainAgeGroupId;
            }

            List<FixtureModel> Fixtures = db.Fixtures.Where(f => f.Team1.DivisionId == DivisionId && f.Team1.AgeGroupId == AgeGroupId && f.Executed == false || f.Matchdate > DateTime.Now).ToList();

            return View(Fixtures);
        }


        // results page
        public ActionResult Results()
        {
            ViewBag.DivisionId = new SelectList(db.Divisions, "DivisionId", "DivisionName");
            ViewBag.AgeGroupId = new SelectList(db.AgeGroup, "AgeGroupId", "AgeGroupName");

            int AgeGroupId, DivisionId;

            //If a division has not been selected when the view all logs link has been clicked on, then use the first division in the table
            if (MainDivisionId == 0)
            {
                DivisionId = db.Divisions.FirstOrDefault().DivisionId;
            }
            else
            {
                DivisionId = MainDivisionId;
            }

            //If a division has not been selected when the view all logs link has been clicked on, then use the first division in the table
            if (MainAgeGroupId == 0)
            {
                AgeGroupId = db.AgeGroup.FirstOrDefault().AgeGroupID;
            }
            else
            {
                AgeGroupId = MainAgeGroupId;
            }

            List<ResultModel> Results = db.Results.Where(r => r.Fixtures.Team1.DivisionId == DivisionId && r.Fixtures.Team1.AgeGroupId == AgeGroupId && r.Fixtures.Executed == false || r.Fixtures.Matchdate > DateTime.Now).ToList();

            return View(Results);
        }

        // Divison Selection Change
        public JsonResult Division(int id)
        {

            int AgeGroupId;

            if (MainAgeGroupId == 0)
            {
                AgeGroupId = db.AgeGroup.FirstOrDefault().AgeGroupID;
            }
            else
            {
                AgeGroupId = MainAgeGroupId;
            }


            MainDivisionId = id;

            

            List<FixtureModel> Fixtures = db.Fixtures.Where(f => f.Team1.Division.DivisionId == id && f.Team1.AgeGroup.AgeGroupID == AgeGroupId).ToList();
            List<ResultModel> Results = db.Results.Where(r => r.Fixtures.Team1.DivisionId == id && r.Fixtures.Team1.AgeGroupId == AgeGroupId).ToList();
            List<LogModel> Logs = db.Logs.Where(l => l.Team.DivisionId == id && l.Team.AgeGroupId == AgeGroupId).ToList();
            SortLogs(Logs);
           // List<TeamModel> Logs = db.Teams.Where(t => t.DivisionId == id && t.AgeGroupId == AgeGroupId).ToList();

            ViewModels.WebsiteIndexViewModel IndexPage = new WebsiteIndexViewModel(Fixtures, Results, Logs);

            //var result = JsonConvert.SerializeObject(IndexPage.Fixtures, Formatting.Indented,
            //    new JsonSerializerSettings
            //    {
            //        ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            //    });

            //result = result + JsonConvert.SerializeObject(IndexPage.Logs, Formatting.Indented,
            //    new JsonSerializerSettings
            //    {
            //        ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            //    });

            //result = result + JsonConvert.SerializeObject(IndexPage.Results, Formatting.Indented,
            //    new JsonSerializerSettings
            //    {
            //        ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            //    });

            return Json(IndexPage, JsonRequestBehavior.AllowGet);

        }

        //Age group selection chnage
        public JsonResult AgeGroup(int id)
        {

            if (MainDivisionId == 0)
            {
                MainDivisionId = db.Divisions.FirstOrDefault().DivisionId;
            }

            MainAgeGroupId = id;

            List<FixtureModel> Fixtures = db.Fixtures.Where(f => f.Team1.Division.DivisionId == MainDivisionId && f.Team1.AgeGroup.AgeGroupID == id).ToList();
            List<ResultModel> Results = db.Results.Where(r => r.Fixtures.Team1.DivisionId == MainDivisionId && r.Fixtures.Team1.AgeGroupId == id).ToList();
            List<LogModel> Logs = db.Logs.Where(l => l.Team.DivisionId == MainDivisionId && l.Team.AgeGroupId == id).ToList();

            SortLogs(Logs);

            WebsiteIndexViewModel IndexPage = new WebsiteIndexViewModel(Fixtures, Results, Logs);

            return Json(IndexPage, JsonRequestBehavior.AllowGet);
        }

        //User Defined Function
        //Sorts the logs according to Points and Goal Difference
        public void SortLogs(List<LogModel> Logs)
        {

            //int Temp;
            LogModel Temp;

            //Sorting according to points
            for (int i = 0; i < Logs.Count() - 1; i++)
            {
                for (int k = i + 1; k < Logs.Count(); k++)
                {
                    if (Logs[i].Points < Logs[k].Points)
                    {

                        Temp = Logs[k];
                        Logs[k] = Logs[i];
                        Logs[i] = Temp;

                        //Temp = Logs[k].LogStanding;
                        //Logs[k].LogStanding = Logs[i].LogStanding;
                        //Logs[i].LogStanding = Temp;

                        //if (ModelState.IsValid)
                        //{
                        //    db.Entry(Logs[i]).State = EntityState.Modified;
                        //    db.Entry(Logs[k]).State = EntityState.Modified;
                        //    db.SaveChanges();
                        //}
                    }
                }
            }

            //if points are the same then sort according to goal difference

            for (int i = 0; i < Logs.Count() - 1; i++)
            {
                for (int k = i + 1; k < Logs.Count(); k++)
                {
                    if (Logs[i].Points == Logs[k].Points)
                    {
                        if (Logs[i].GoalDifference < Logs[k].GoalDifference)
                        {

PHSS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />

    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PHSS", "Index", "Website", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Fixtures", "Fixtures", "Website")</li>
                    <li>@Html.ActionLink("Results", "Results", "Website")</li>
                    <li>@Html.ActionLink("Logs", "Logs", "Website")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    @*<div class="body-content"> @*I removed the container class from here*@

    @RenderBody()

    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>

    @*</div>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PHSS/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />

    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PHSS", "Index", "Website", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Fixtures", "Fixtures", "Website")</li>
                    <li>@Html.ActionLink("Results", "Results", "Website")</li>
                    <li>@Html.ActionLink("Logs", "Logs", "Website")</li>
                    <li>@Html.ActionLink("Manage", "Index", "Data")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>